[package]
name = "youchoose_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#youchoose = "0.1.1"
termion = { version = "1.5.6", optional = true }
tui = "0.16.0"